name: Deploy to Hugging Face Space
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install latest huggingface_hub
        run: pip install --force-reinstall "huggingface_hub[hf_transfer]"

      - name: Sync repo to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python - <<'PY'
          import os
          from huggingface_hub import HfApi

          api = HfApi(token=os.environ["HF_TOKEN"])

          print("Token validated, attempting to upload...")

          api.upload_folder(
              repo_id="bladevil/zhilv-ai-server",
              repo_type="space",
              folder_path=".",
              path_in_repo=".",
              commit_message="Sync from GitHub"
          )
          print("Upload command sent successfully.")
          PY
