name: Sync to Hugging Face Space (via git)
on:
  push:
    branches: [ "main" ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure git identity
        run: |
          git config user.name  "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          set -e
          test -n "$HF_TOKEN" || { echo "HF_TOKEN 未设置（Settings → Secrets and variables → Actions）"; exit 1; }

          HF_REMOTE="https://bladevil:${HF_TOKEN}@huggingface.co/spaces/bladevil/zhilv-ai-server"

          if git remote | grep -q '^hf$'; then
            git remote set-url hf "$HF_REMOTE"
          else
            git remote add hf "$HF_REMOTE"
          fi

          # 推到 Space 的 main 分支
          git push hf HEAD:main --force-with-lease
          echo "✅ 已推送到 Hugging Face Space。打开 Space 的 Logs 查看构建。"
