name: Deploy to Hugging Face Space
on:
  push:
    branches: [ "main" ]   # 如果默认分支不是 main，这里改成你的分支名

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install huggingface_hub
        run: pip install huggingface_hub

      - name: Sync repo to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}   # 你在 Settings/Secrets 里添加的 token
        run: |
          python - <<'PY'
          import os
          from huggingface_hub import HfApi
          api = HfApi(token=os.environ["HF_TOKEN"])
          api.upload_folder(
              repo_id="bladevil/zhilv-ai-server",  # 你的 Space 路径
              repo_type="space",
              folder_path=".",                      # 代码所在目录；若在子目录就改成例如 "server"
              path_in_repo=".",
              commit_message="Sync from GitHub"
          )
          PY
